apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-guestbook
  namespace: argocd
spec:
  project: guestbook

  source:
    repoURL: 'file:////mount/git-repo.git'
    path: app-guestbook
    targetRevision: main

  destination:
    name: in-cluster
    namespace: guestbook

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
