repoServer:
  volumes:
    - name: local-repo
      hostPath:
        path: /home/pkoch/Documents/github/pauloricardokoch/argocd-lab/git-repo/
        type: Directory
    - name: git-config-volume
      configMap:
        name: argocd-global-git-config
        items:
          - key: gitconfig
            path: gitconfig

  volumeMounts:
    - name: local-repo
      mountPath: /mount/git-repo.git
    - name: git-config-volume
      mountPath: /etc/gitconfig
      subPath: gitconfig
